# Generated by Django 4.1.7 on 2023-04-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_remove_orderitem_book_store_id_orderitem_book_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.book'),
            preserve_default=False,
        ),
    ]
