# Generated by Django 4.1.7 on 2023-04-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_id_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='book',
            name='warehouse_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
